//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orc.LicenseManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orc.LicenseManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutHeader {
            get {
                return ResourceManager.GetString("AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to buy a license.
        /// </summary>
        internal static string ClickToBuyLicense {
            get {
                return ResourceManager.GetString("ClickToBuyLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete license.
        /// </summary>
        internal static string DeleteLicense {
            get {
                return ResourceManager.GetString("DeleteLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save license. Please try again or pick a different location..
        /// </summary>
        internal static string FailedToSaveLicense {
            get {
                return ResourceManager.GetString("FailedToSaveLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert license.
        /// </summary>
        internal static string InsertLicenseHeader {
            get {
                return ResourceManager.GetString("InsertLicenseHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License management.
        /// </summary>
        internal static string LicenceManagementHeader {
            get {
                return ResourceManager.GetString("LicenceManagementHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License for:.
        /// </summary>
        internal static string LicenseManager_LicenseView_TextBlock_Text_LicenseFor {
            get {
                return ResourceManager.GetString("LicenseManager_LicenseView_TextBlock_Text_LicenseFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy more licenses.
        /// </summary>
        internal static string LicenseManager_NetworkLicenseUsageWindow_Button_Content_BuyMoreLicenses {
            get {
                return ResourceManager.GetString("LicenseManager_NetworkLicenseUsageWindow_Button_Content_BuyMoreLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application.
        /// </summary>
        internal static string LicenseManager_NetworkLicenseUsageWindow_Button_Content_CloseApplication {
            get {
                return ResourceManager.GetString("LicenseManager_NetworkLicenseUsageWindow_Button_Content_CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are entitled to {0} concurrent usages of the license, but it looks this amount is already used..
        /// </summary>
        internal static string LicenseManager_NetworkLicenseUsageWindow_TextBlock_ConverterParameter_YouAreEntitledToConcurrentUsagesOfTheLicenseButItLooksThisAmountIsAlreadyUsed {
            get {
                return ResourceManager.GetString("LicenseManager_NetworkLicenseUsageWindow_TextBlock_ConverterParameter_YouAreEntit" +
                        "ledToConcurrentUsagesOfTheLicenseButItLooksThisAmountIsAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below is a list of current usages of your license. You can wait for a license to become available by keeping this window open. To speed up the process, you can contact one of the persons below to ask them to close the software. .
        /// </summary>
        internal static string LicenseManager_NetworkLicenseUsageWindow_TextBlock_Text_BelowIsAListOfCurrentUsagesOfYourLicenseYouCanWaitForALicenseToBecomeAvailableByKeepingThisWindowOpenToSpeedUpTheProcessYouCanContactOneOfThePersonsBelowToAskThemToCloseTheSoftware {
            get {
                return ResourceManager.GetString("LicenseManager_NetworkLicenseUsageWindow_TextBlock_Text_BelowIsAListOfCurrentUsag" +
                        "esOfYourLicenseYouCanWaitForALicenseToBecomeAvailableByKeepingThisWindowOpenToSp" +
                        "eedUpTheProcessYouCanContactOneOfThePersonsBelowToAskThemToCloseTheSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that you have reached the maximum number of concurrent usages of the license..
        /// </summary>
        internal static string LicenseManager_NetworkLicenseUsageWindow_TextBlock_Text_ItAppearsThatYouHaveReachedTheMaximumNumberOfConcurrentUsagesOfTheLicense {
            get {
                return ResourceManager.GetString("LicenseManager_NetworkLicenseUsageWindow_TextBlock_Text_ItAppearsThatYouHaveReach" +
                        "edTheMaximumNumberOfConcurrentUsagesOfTheLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License properties.
        /// </summary>
        internal static string LicensePropsHeader {
            get {
                return ResourceManager.GetString("LicensePropsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No text was pasted into the window.
        /// </summary>
        internal static string NoTextWasPasted {
            get {
                return ResourceManager.GetString("NoTextWasPasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (CTRL + V).
        /// </summary>
        internal static string PasteWithShortcut {
            get {
                return ResourceManager.GetString("PasteWithShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please paste the whole license in this window to verify the license..
        /// </summary>
        internal static string PleasePaste {
            get {
                return ResourceManager.GetString("PleasePaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show clipboard.
        /// </summary>
        internal static string ShowClipboard {
            get {
                return ResourceManager.GetString("ShowClipboard", resourceCulture);
            }
        }
    }
}
